Migrate to WXT
GorvGoyl/Notion-Boost-browser-extension pull request #224
Opened 2024-08-20 15:43 UTC by arnab710

1. Convert from JS to TS.
2. Migrate to WXT from webpack

2024-08-20 15:51 UTC, arnab710 commented
@Anshtripathi079 @GorvGoyl This will be the new file structure.

@Anshtripathi079 I have already removed some code related to ExtPay. Could you please remove all `extPay` related codes in this PR? So, We don't have to deal with 2 different PRs.

2024-08-28 11:26 UTC, GorvGoyl requested changes
let's prevent opening a new browser when running `dev` command

2024-08-28 11:41 UTC, GorvGoyl reviewed
when running `pnpm run package`, output should be 3 zip files with following names (no need to add version info):
1. notion_boost_chrome.zip
2. notion_boost_firefox.zip
3. notion_boost_sourcecode.zip

2024-08-28 11:46 UTC, GorvGoyl commented
Also, the prettier extension is not working properly 
![screenshot 2024-08-28 at 13 45 51@2x](https://github.com/user-attachments/assets/5fcb1b35-73b2-4c28-89ae-09560e7f2215)

2024-08-28 11:48 UTC, GorvGoyl commented on components/features/openFullPage.ts
>          ...fullPageLink.pathname.split(/(-|\/)/g).reverse(),
ts errors in this file: Property 'pathname' does not exist on type 'Element'.

2024-09-09 08:19 UTC, merged